# PVC donde Prometheus guarda sus métricas para no perderlas al reiniciar
# Pide 5Gi usando la StorageClass de NFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
