# Inventario de nodos del cluster CapiShop
# Define los tres nodos y en qué grupo va cada uno

[all:vars]
ansible_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Nodo master — controla el cluster
[k8s_master]
capishop-master01 ansible_host=192.168.224.135

# Nodos worker — donde corren los contenedores de la aplicación
[k8s_workers]
capishop-worker01 ansible_host=192.168.224.136
capishop-worker02 ansible_host=192.168.224.137

# Grupo que incluye todos los nodos
[k8s_cluster:children]
k8s_master
k8s_workers

# Variables que aplican a todos los nodos del cluster
[k8s_cluster:vars]
k8s_version=1.28
pod_network_cidr=10.244.0.0/16
