# Service interno (ClusterIP) de Loki
# Por aquí Promtail le manda los logs y Grafana los consulta, en el 3100
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
