apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  MONGODB_URI: "mongodb://admin:capishop123@mongodb-0.mongodb.default.svc.cluster.local:27017,mongodb-1.mongodb.default.svc.cluster.local:27017,mongodb-2.mongodb.default.svc.cluster.local:27017/capishop?replicaSet=rs0&authSource=admin"
  PORT: "3000"
  NODE_ENV: "production"
